// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXAtJpD0IqlNpMXwY4Oacq8E1D3eDaOSE',
    appId: '1:808793774900:web:3e1642e9a278af4071a361',
    messagingSenderId: '808793774900',
    projectId: 'base-app-6d46e',
    authDomain: 'base-app-6d46e.firebaseapp.com',
    databaseURL: 'https://base-app-6d46e-default-rtdb.firebaseio.com',
    storageBucket: 'base-app-6d46e.firebasestorage.app',
    measurementId: 'G-6JHYFG2BEX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYspkLipEQTtDZl6LMBunyTuqKOxYWA20',
    appId: '1:808793774900:android:adfe8d3bc64a02b271a361',
    messagingSenderId: '808793774900',
    projectId: 'base-app-6d46e',
    databaseURL: 'https://base-app-6d46e-default-rtdb.firebaseio.com',
    storageBucket: 'base-app-6d46e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTt3w-Ov6gNby9qbWxyzSHPk5iO_wJhYo',
    appId: '1:808793774900:ios:2ce0272abb16d34371a361',
    messagingSenderId: '808793774900',
    projectId: 'base-app-6d46e',
    databaseURL: 'https://base-app-6d46e-default-rtdb.firebaseio.com',
    storageBucket: 'base-app-6d46e.firebasestorage.app',
    iosBundleId: 'com.example.expanda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTt3w-Ov6gNby9qbWxyzSHPk5iO_wJhYo',
    appId: '1:808793774900:ios:2ce0272abb16d34371a361',
    messagingSenderId: '808793774900',
    projectId: 'base-app-6d46e',
    databaseURL: 'https://base-app-6d46e-default-rtdb.firebaseio.com',
    storageBucket: 'base-app-6d46e.firebasestorage.app',
    iosBundleId: 'com.example.expanda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXAtJpD0IqlNpMXwY4Oacq8E1D3eDaOSE',
    appId: '1:808793774900:web:3286b55b1488a00871a361',
    messagingSenderId: '808793774900',
    projectId: 'base-app-6d46e',
    authDomain: 'base-app-6d46e.firebaseapp.com',
    databaseURL: 'https://base-app-6d46e-default-rtdb.firebaseio.com',
    storageBucket: 'base-app-6d46e.firebasestorage.app',
    measurementId: 'G-J4L44DC8VG',
  );
}
